InvalidFilterError: Rename to FilterNotFoundError
For better accordance with standard Python exception naming schemes

Closes https://github.com/coala/coala/issues/4872